// <auto-generated />
using System;
using BlackhawkDesign.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlackhawkDesign.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240101190544_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlackhawkDesign.Data.Models.Application", b =>
                {
                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("Applied")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("AttachmentHash")
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)");

                    b.Property<string>("AttachmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("AttachmentSize")
                        .HasColumnType("bigint");

                    b.Property<string>("AttachmentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverLetter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NormalizedName");

                    b.ToTable("Applications", (string)null);
                });

            modelBuilder.Entity("BlackhawkDesign.Data.Models.ApplicationAttachmentContent", b =>
                {
                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("NormalizedName");

                    b.ToTable("Applications", (string)null);
                });

            modelBuilder.Entity("BlackhawkDesign.Data.Models.Job", b =>
                {
                    b.Property<string>("JobName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("JobBenefit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qualifications")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobName");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("BlackhawkDesign.Data.Models.JobApplication", b =>
                {
                    b.Property<int>("JobApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobApplicationId"));

                    b.Property<string>("ApplicationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("JobId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("JobApplicationId");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("JobId");

                    b.ToTable("JobApplications");
                });

            modelBuilder.Entity("BlackhawkDesign.Data.Models.ApplicationAttachmentContent", b =>
                {
                    b.HasOne("BlackhawkDesign.Data.Models.Application", null)
                        .WithOne("AttachmentContent")
                        .HasForeignKey("BlackhawkDesign.Data.Models.ApplicationAttachmentContent", "NormalizedName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BlackhawkDesign.Data.Models.JobApplication", b =>
                {
                    b.HasOne("BlackhawkDesign.Data.Models.Application", "Application")
                        .WithMany("JobApplied")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BlackhawkDesign.Data.Models.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Application");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("BlackhawkDesign.Data.Models.Application", b =>
                {
                    b.Navigation("AttachmentContent");

                    b.Navigation("JobApplied");
                });
#pragma warning restore 612, 618
        }
    }
}
